# Advanced Momentum Strategy Configuration

strategies:
  # Intermediate-term momentum (2-8 weeks)
  intermediate_momentum:
    enabled: true
    timeframe: "intermediate"
    lookback_period: 252  # 1 year of data required
    top_n: 15  # Number of positions
    rebalance_frequency: "weekly"
    
    # Holding periods
    min_holding_period: 14  # 2 weeks minimum
    max_holding_period: 56  # 8 weeks maximum
    
    # Moving averages
    ma_short: 20
    ma_medium: 50
    ma_long: 200
    
    # Entry criteria
    min_price_performance: 0.10  # 10% minimum 1-month return
    volume_surge_threshold: 1.5  # 50% above average volume
    rsi_min: 50  # Minimum RSI
    rsi_max: 75  # Maximum RSI (avoid extreme overbought)
    
    # Exit criteria
    trailing_stop_ma: 20  # Exit if closes below 20-day MA
    
    # Risk management
    max_position_size: 0.067  # ~15 positions = 100%
    stop_loss_pct: 0.07  # 7% stop loss
    
    # Filters
    min_price: 10.0  # Minimum stock price
    min_volume: 1000000  # Minimum daily volume ($)
    
  # Long-term momentum (2-6 months)
  long_term_momentum:
    enabled: true
    timeframe: "long_term"
    lookback_period: 252  # 1 year of data required
    top_n: 10  # Fewer positions for longer holding
    rebalance_frequency: "monthly"
    
    # Holding periods
    min_holding_period: 60  # 2 months minimum
    max_holding_period: 180  # 6 months maximum
    
    # Moving averages
    ma_short: 20
    ma_medium: 50
    ma_long: 200
    
    # Entry criteria
    min_price_performance: 0.15  # 15% minimum 1-month return
    volume_surge_threshold: 1.3  # 30% above average volume
    rsi_min: 55  # Higher minimum RSI for long-term
    rsi_max: 70  # Lower maximum to avoid extremes
    
    # Exit criteria
    weekly_ma_exit: 50  # Exit if closes below 50-day MA (weekly equivalent)
    
    # Risk management
    max_position_size: 0.10  # 10% per position
    stop_loss_pct: 0.10  # 10% stop loss (wider for long-term)
    
    # Filters
    min_price: 15.0  # Higher minimum for quality
    min_volume: 2000000  # Higher liquidity requirement

# Screening parameters for stock universe
screening:
  # Universe selection
  universe:
    - "S&P 500"  # Can be expanded to other indices
    
  # Initial filters
  filters:
    market_cap_min: 1000000000  # $1B minimum
    average_volume_min: 500000  # shares
    price_min: 5.0
    
  # Technical requirements
  technical:
    days_above_ma50: 20  # Must be above 50-day MA for 20 days
    relative_strength_min: 1.1  # 10% outperformance vs SPY
    
  # Fundamental momentum (optional)
  fundamental:
    earnings_growth_min: 0.10  # 10% YoY earnings growth
    revenue_growth_min: 0.05  # 5% YoY revenue growth
    estimate_revisions: "positive"  # Positive analyst revisions

# Sector and correlation limits
risk_limits:
  max_sector_exposure: 0.30  # 30% maximum in any sector
  max_correlation: 0.70  # Maximum correlation between positions
  max_drawdown: 0.15  # 15% maximum drawdown trigger
